### ISSUE TITLE
Can I execute code on Mac OSX? 

### ISSUE THREAD

**Issue by advaza** [MingMingCheng/CmCode#7]
Hi, 
I understand that the code is written with windows visual studio and some of the libraries are VS libraries, and was wondering - is it possible to run the code on Mac OSX? 
If so, what are the changes I need to do and how to compile the code?

Thanks a lot!
Adva

**Comment by MingMingCheng** [comment]
I'm not familiar with compiling in Mac OSX. Sorry

**Comment by edwardnguyen1705** [comment]
Hi @MingMingCheng ,
Which opencv version you used?
Thanks.

**Comment by MingMingCheng** [comment]
I haven't updated this code for quite a few years. I was using 2.x versions and they were working fine.

**Comment by edwardnguyen1705** [comment]
Hi @MingMingCheng ,
Thank you.
