### ISSUE TITLE
RC算法显著性试验C++代码中有一个类的定义找不到

### ISSUE THREAD

**Issue by JackeyDeng** [MingMingCheng/CmCode#8]
老师您好，我在做RC算法检测显著性时发现里面用到了一个Region类，这个类似乎是你们自己定义的，但是我找了很多头文件都没有看到这个类的定义，请问它的定义在哪里呢，谢谢！

**Comment by MingMingCheng** [comment]
在这个文件的第50行：https://github.com/MCG-NKU/CmCode/blob/master/CmLib/Saliency/CmSaliencyRC.h
